content: 
  version: 3.7
  command: pet
  probability: 30
  antialias: true
  disabled: []
  keyCommand: true
  keyCommandHead: ''
  commandMustAt: false
  respondImage: true
  respondSelfNudge: false
  fuzzy: false
  synchronized: false
  headless: true
  autoUpdate: true
  repositoryUrl: 'https://dituon.github.io/petpet'